const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Pin,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.shadowlight,
		C3.Behaviors.Sin,
		C3.Plugins.iframe,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Spritefont2,
		C3.Plugins.sliderbar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Acts.FallThrough,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetPos
	];
};
self.C3_JsPropNameTable = [
	{Pin: 0},
	{slimeClouds: 0},
	{Solid: 0},
	{straightfloor: 0},
	{Lives: 0},
	{"8Direction": 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Glorb: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{ShadowLight: 0},
	{Orientation: 0},
	{Sine: 0},
	{Enemy: 0},
	{skinnyAround: 0},
	{iframe: 0},
	{burger: 0},
	{menuBg: 0},
	{Sprite: 0},
	{spikes: 0},
	{sticktooLeftright: 0},
	{blankFloor: 0},
	{MonsterCollision: 0},
	{Audio: 0},
	{goToNextLevel: 0},
	{coin: 0},
	{score: 0},
	{stillCoin: 0},
	{gameOverBg: 0},
	{Restart: 0},
	{Sprite2: 0},
	{Button: 0},
	{DRAWINGS: 0},
	{Touch: 0},
	{Sprite3: 0},
	{Browser: 0},
	{Sprite4: 0},
	{narrator: 0},
	{SpriteFont: 0},
	{Sprite6: 0},
	{bigAroundFloor2: 0},
	{STOPstick: 0},
	{sticktooupdown: 0},
	{Sprite5: 0},
	{settings: 0},
	{SliderBar: 0},
	{TiledBackground: 0},
	{SliderBar2: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{progress: 0},
	{required: 0},
	{LastLevelPlayed: 0}
];

self.InstanceType = {
	slimeClouds: class extends self.ITiledBackgroundInstance {},
	straightfloor: class extends self.ITiledBackgroundInstance {},
	Glorb: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	ShadowLight: class extends self.IShadowLightInstance {},
	Enemy: class extends self.ISpriteInstance {},
	skinnyAround: class extends self.ITiledBackgroundInstance {},
	iframe: class extends self.IIframeInstance {},
	burger: class extends self.ISpriteInstance {},
	menuBg: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	spikes: class extends self.ITiledBackgroundInstance {},
	sticktooLeftright: class extends self.ITiledBackgroundInstance {},
	blankFloor: class extends self.ITiledBackgroundInstance {},
	MonsterCollision: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	goToNextLevel: class extends self.ITiledBackgroundInstance {},
	coin: class extends self.ISpriteInstance {},
	score: class extends self.ITextInstance {},
	stillCoin: class extends self.ISpriteInstance {},
	Lives: class extends self.ISpriteInstance {},
	gameOverBg: class extends self.ITiledBackgroundInstance {},
	Restart: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	DRAWINGS: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	narrator: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	bigAroundFloor2: class extends self.ITiledBackgroundInstance {},
	STOPstick: class extends self.ITiledBackgroundInstance {},
	sticktooupdown: class extends self.ITiledBackgroundInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	settings: class extends self.ISpriteInstance {},
	SliderBar: class extends self.ISliderBarInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	SliderBar2: class extends self.ISliderBarInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {}
}